import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1:30080';
const FRONTEND_URL = __ENV.FRONTEND_URL || 'http://127.0.0.1:43829';
const LOGIN_EMAIL = __ENV.LOGIN_EMAIL || 'admin@test.com';
const LOGIN_PASSWORD = __ENV.LOGIN_PASSWORD || '000333him';

export const options = {
  stages: [
    { duration: '30s', target: 3  },
    { duration: '4m',  target: 8  },
    { duration: '2m',  target: 8  },
    { duration: '30s', target: 0  },
  ],
  thresholds: {
    http_req_duration: ['p(95)<2000'],
  },
};

export function setup() {
  const res = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify({
    email: LOGIN_EMAIL,
    password: LOGIN_PASSWORD,
  }), { headers: { 'Content-Type': 'application/json' } });

  const token = res.json('token');
  if (!token) {
    console.error(`Login failed: ${res.status} ${res.body}`);
  }
  return { token };
}

export default function (data) {
  const headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${data.token}`,
  };

  const action = Math.random();

  if (action < 0.1) {
    // фронтенд — главная страница
    const res = http.get(`${FRONTEND_URL}/`, { headers: { 'Accept': 'text/html' } });
    check(res, { 'frontend 200': (r) => r.status === 200 });
  } else if (action < 0.55) {
    // SELECT — список записей
    const res = http.get(`${BASE_URL}/api/diary`, { headers });
    check(res, { 'list 200': (r) => r.status === 200 });
  } else if (action < 0.8) {
    // INSERT — создание записи
    const res = http.post(`${BASE_URL}/api/diary`, JSON.stringify({
      title: `Load test entry ${Date.now()}`,
      content: 'Generated by k6 load test',
    }), { headers });
    check(res, { 'create 201': (r) => r.status === 201 });
  } else {
    // SELECT — профиль пользователя
    const res = http.get(`${BASE_URL}/api/auth/me`, { headers });
    check(res, { 'me 200': (r) => r.status === 200 });
  }

  sleep(1);
}
