sonar.projectKey=Philasterion-DevOps
sonar.projectName=Philasterion DevOps

sonar.sources=app,resources/js
sonar.tests=tests,resources/js/tests

sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,coverage/**,resources/js/tests/**

sonar.coverage.exclusions=\
  resources/js/views/**,\
  resources/js/layouts/**,\
  resources/js/router/**,\
  resources/js/App.vue,\
  resources/js/app.js,\
  resources/js/bootstrap.js,\
  resources/js/api/**,\
  app/Console/**,\
  app/Exceptions/**,\
  app/Http/Middleware/**,\
  app/Http/Kernel.php,\
  app/Providers/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true

