apiVersion: v1
kind: ConfigMap
metadata:
  name: philasterion-config
  namespace: philasterion
data:
  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: laravel_devops
  DB_USERNAME: laravel
  APP_ENV: production
  APP_DEBUG: "false"
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  QUEUE_CONNECTION: sync