apiVersion: v1
kind: Secret
metadata:
  name: philasterion-secrets
  namespace: philasterion
type: Opaque
stringData:
  DB_PASSWORD: "secret"
  DB_ROOT_PASSWORD: "root_secret"
  APP_KEY: "base64:hEFLxEi6ap9zkNrZ3P/i8gqzq7f1oRV31rz68yErel8="
  GITHUB_TOKEN: "REPLACE_WITH_YOUR_GITHUB_TOKEN"
